#!/usr/bin/env bash

source invert-import.sh

main() {
  proj_name="${1%.gif}"
  trap "cleanup $proj_name; exit 1" SIGQUIT SIGINT SIGTERM
  make_pngs "$proj_name"
  invert_pngs "$proj_name" $2 $3 $4
  make_gif "$proj_name"
  cleanup "$proj_name"
  exit 0;
}

if [[ $1 == "" ]]; then echo "error: no arguments"; exit 1; fi
main $1 $2 $3 $4
